name: PR Code Format Check
on:
  workflow_dispatch:
jobs:
  check-code-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch source
        uses: actions/checkout@v4

      - name: Check for installed rust tools
        run: |
          rustup --version
          rustup toolchain list

      - name: Get nightly toolchain and set it as default
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup component add rustfmt

      - name: Check rust tool versions
        run: |
          rustup toolchain list
          rustfmt --version

      - run: echo "status = ${{ job.status }}"
