name: PR Code Format Check
on:
  workflow_dispatch:
jobs:
  check-code-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch source
        uses: actions/checkout@v4
        
      - name: Install nightly rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - run: rustfmt --help
      - run: rustup toolchain list
      - run: echo "status = ${{ job.status }}"
