name: rustfmt_check
on:
  workflow_dispatch:
jobs:
  rustfmt_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch source
        uses: actions/checkout@v4

      - name: Check for pre-installed rustup
        run: |
          rustup --version
          rustup toolchain list

      - name: Install rustfmt from nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup component add rustfmt

      - name: Check rustfmt version
        run: |
          rustfmt --version

      - name: Run rustfmt
        run: rustfmt --check

      - run: echo "status = ${{ job.status }}"
