name: rustfmt_check
on:
  workflow_dispatch:
jobs:
  rustfmt_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch source
        uses: actions/checkout@v4

      - name: Make a new crate
        run: |
          cargo new autofmt_demo
          head -n 1000 Cargo.toml src/main.rs
        
      - name: Install rustfmt from nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup component add rustfmt
          rustfmt --version

      - name: Run cargo fmt -- --check
        run: cargo fmt -- --check

      - run: echo "status = ${{ job.status }}"
