name: rustfmt_check
on: [push, pull_request]
jobs:
  rustfmt_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch source
        uses: actions/checkout@v4

      - name: Install rustfmt from nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly

      - name: Run cargo +nightly fmt --check
        run: cargo +nightly fmt --check

      - run: echo "status = ${{ job.status }}"
