name: trailing_whitespace_check
on: push
jobs:
  trailing_whitespace_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch source
        uses: actions/checkout@v4

      - name: Check .rs files for trailing whitespace
        run: >
          find . -name '*.rs' -print0 | xargs -0 grep -c '[ \t]$'
          | grep -v ':0$'
          | perl -e 'while($x=<>){print $x;$n+=1};if($n>0){print "FAIL $n\n";exit 1;};print "PASS $n\n";exit 0;'
