name: trailing_whitespace_check
on: push
jobs:
  trailing_whitespace_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch source
        uses: actions/checkout@v4

      - name: Check .rs files for trailing whitespace
        run: >
          find . -name '*.rs'
